my:
  greeting: Hello World from Config Server
  list:
    values: One, Two, Three

db:
  connection: connection-string-from-config-server
  host: 127.0.0.1
  password: '{cipher}a42755b88c05b7d4d9e5b54a3fea8691aa4e1bdd4ab90e8d01fe8de5143a674b'
  port: 1200

secondary:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: 
    driverClassName: org.h2.Driver
    properties:
      hibernate.hbm2ddl.auto: update
